version: '{branch}.{build}'
shallow_clone: false
platform: x64
skip_branch_with_pr: true

clone_folder: C:\gopath\src\github.com\DataDog\datadog-agent-six

# environment must be set for python 64 bit
environment:
  GOPATH: C:\gopath
  GOROOT: C:\go111
  RUBY_PATH: C:\Ruby23-x64
  RI_DEVKIT: C:\Ruby23-x64\DevKit\

install:
  - set PATH=%GOPATH%\bin;C:\%GOPATH%\bin;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\;%RUBY_PATH%\bin;%RI_DEVKIT%bin;%RI_DEVKIT%mingw\bin;c:\python27-x64;c:\python27-x64\scripts;c:\python37-x64;c:\python37-x64\scripts;%PATH%
  - set PATH=%PATH%;
  - echo cd is %CD%
  - go version
  - python --version
  - c:\python37-x64\python --version
  - gcc --version

cache:
  - '%GOPATH%\bin'
  - '%GOPATH%\src\github.com\DataDog\datadog-agent\vendor'

build: off

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo %Python3_ROOT_DIR%
  - cmake -G "Unix Makefiles" -BUILD_DEMO:bool=OFF .
  - set PATH=%PATH%;%CD%\bin
  - make
  - make clang-format
  - make -C test
